#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "../inc/crc32.h"
#include "../inc/flash.h"

#define APP_START_ADDR 0x08004000
#define APP_SIZE 0x20000
#define CRC_SIZE 4



// Simulate jump to application
void jump_to_application(uint8_t *app, uint32_t size) {
    uint32_t stored_crc;
    memcpy(&stored_crc, app + size - CRC_SIZE, CRC_SIZE);
    uint32_t calc_crc = crc32(app, size - CRC_SIZE);
    if (stored_crc == calc_crc) {
        printf("[Bootloader] Jumping to application at fake flash address... CRC OK!\n");
    } else {
        printf("[Bootloader] [ERROR] Application invalid! Staying in bootloader\n");
    }
}

void bootloader_main() {
    printf("Bootloader started...\n");
    printf("[Bootloader] Erasing flash...\n");

    flash_erase(0, APP_SIZE + CRC_SIZE);
    /*
    for (uint32_t i = 0; i < APP_SIZE; i++){
        uint8_t byte = i & 0xFF;
        flash_write(i, &byte, 1);
    }
    */
    // THIS VERSION loads app.bin generated by our python tool
    printf("[Bootloader] Loading firmware from app.bin...\n");
    FILE *f = fopen("app.bin", "rb");
    if (!f){
        printf("[Bootloader] [ERROR] Failed to open app.bin\n");
        return;
    }

    uint8_t buffer[1024];
    uint32_t addr = 0;
    size_t n;

    while ((n = fread(buffer, 1 , sizeof(buffer), f))){
        flash_write(addr, buffer, n);
        addr += n;
    }

    fclose(f);
    printf("[Bootloader] Firmware loaded: %u bytes\n", addr);

    printf("[Bootloader] Verifying CRC...\n");
    uint32_t stored_crc;
    flash_read(APP_SIZE, (uint8_t *)&stored_crc, CRC_SIZE);
    uint32_t calc_crc = crc32(flash_memory, APP_SIZE);
    printf("[Bootloader] Stored CRC: 0x%08X, Calculated CRC: 0x%08X\n", stored_crc, calc_crc);
    if (calc_crc == stored_crc) {
        printf("[Bootloader] CRC OK!\n");
    } else {
        printf("[Bootloader] CRC FAIL! 0x%08X vs 0x%08X\n", calc_crc, stored_crc);
    }

    jump_to_application(flash_memory, APP_SIZE + CRC_SIZE);
}
